######################################################
## Author: ANIMIKH AICH (animikhaich@gmail.com)     ##
## 12 January 2018                                  ##
## Google Translate Using Python                    ##
## RNS Institute of Technology, Bengaluru, India    ##
######################################################

from selenium import webdriver
import time
import warnings

# To ignore the warning generated by PhantomJS -- Not officially supported by Selenium
warnings.filterwarnings("ignore")

# List of Languages supported
lang_list = ['afrikaans','af',
             'irish','ga',
             'albanian','sq',
             'italian','it',
             'arabic','ar',
             'japanese','ja',
             'azerbaijani','az',
             'kannada','kn',
             'basque','eu',
             'korean','ko',
             'bengali','bn',
             'latin','la',
             'belarusian','be',
             'latvian','lv',
             'bulgarian','bg',
             'lithuanian','lt',
             'catalan','ca',
             'macedonian','mk',
             'chinese simplified','zh-cn',
             'malay','ms',
             'chinese traditional','zh-tw',
             'maltese','mt',
             'croatian','hr',
             'norwegian','no',
             'czech','cs',
             'persian','fa',
             'danish','da',
             'polish','pl',
             'dutch','nl',
             'portuguese','pt',
             'english','en',
             'romanian','ro',
             'esperanto','eo',
             'russian','ru',
             'estonian','et',
             'serbian','sr',
             'filipino','tl',
             'slovak','sk',
             'finnish','fi',
             'slovenian','sl',
             'french','fr',
             'spanish','es',
             'galician','gl',
             'swahili','sw',
             'georgian','ka',
             'swedish','sv',
             'german','de',
             'tamil','ta',
             'greek','el',
             'telugu','te',
             'gujarati','gu',
             'thai','th',
             'haitian creole','ht',
             'turkish','tr',
             'hebrew','iw',
             'ukrainian','uk',
             'hindi','hi',
             'urdu','ur',
             'hungarian','hu',
             'vietnamese','vi',
             'icelandic','is',
             'welsh','cy',
             'indonesian','id',
             'yiddish','yi']

# Take input from the user and convert the language to lower for easy detection
myInput = input('Enter the text to be translated: ')
language = input('Enter the language to be translated to: ')
print('Please wait....')
myLang = language.lower()

# Find index of the desired language from the list
# Set the url language code as per selected language
index = lang_list.index(myLang)
if index%2 == 0:
    to_lang = lang_list[index+1]
else:
    to_lang = lang_list[index]

# Construct the complete URL to search
base_url = 'https://translate.google.com/#'
from_lang = 'en'
final_url = base_url + from_lang + '/' + to_lang

# Initialize Selenium Driver
# PhantomJS is used, Chrome is kept as backup for debugging
driver = webdriver.PhantomJS('.\\Selenium Web Drivers\\phantomjs.exe')
# driver = webdriver.Chrome('.\\Selenium Web Drivers\\chromedriver.exe')

# Perform operation to detect the translated text
driver.set_page_load_timeout(30)        # Incase Page doesn't load
driver.get(final_url)                   # Search the URL
driver.find_element_by_name('text').send_keys(myInput)  # Input the Desired text to be translated
driver.find_element_by_id('gt-submit').click()          # Click on the translate button (not Mandatory)
text_output = driver.find_element_by_id('result_box')   # Get the output text

time.sleep(1)   # Else it does not print the data
print(text_output.text)
driver.quit()
